### ISSUE TITLE
[BUG] Symbols Sidebar requires setup

### ISSUE THREAD

**Issue by th3r00t** [doom-neovim/doom-nvim#411]
### Current Behavior:
Upon fresh install when one attempts to open symbol view the following error will occur

`
E5108: Error executing lua ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:171: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/pa
cker/load.lua:83: Vim(lua):E5108: Error executing lua .../packer/opt/symbols-outline.nvim/lua/symbols-outline.lua:307: attempt to index field 'view' (a nil value)
stack traceback:
        [C]: in function 'cmd'
        ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:171: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:167>
        [string ":lua"]:1: in main chunk
`

Example: steps to reproduce the behavior:
1. Fresh Install
2. Enable Symbols save & restart
3. Run 'PackerInstall'
4. Restart Nvim, Toggle symbols
### Expected Behavior:

Symbols Side Bar Opens

### Anything else:
`require("symbols-outline").setup()` is required to get the symbols system functioning, and it doesnt appear to be included. 

I am unable to add it to my config, as i cant discern how to get it to run post plugin loading. 

You can run it via `:lua require("symbols-outline").setup() <CR>` in-situ, and everything functions as expected.

**Comment by molleweide** [comment]
im working on fixing this. it also bugs me that the symbols plug doesnt work atm.

**Comment by pauldub** [comment]
This should be fixed by this commit https://github.com/doom-neovim/doom-nvim/commit/73d1d62f3951954f7a0c8eb85ffce7d1d5ab7e23 merged with #432
